auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: slade
url: http://sladewang.github.com
feed: /atom.xml
author_info: <a href="http://sladewang.github.com/">slade</a>
